---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
require(cowplot)
options(stringsAsFactors = F)
options(scipen = 10000)

data <-  read.table('../../processed_data/endo_scramble/endo_scramble_expression_formatted_std.txt', 
                             header = T)
ttest <- read.table('../../processed_data/endo_scramble/endo_scramble_ttests.txt', header = T)

data <- left_join(data, select(ttest, -tss_name), by = 'name')
#scrambled_merged <- read.table("../../processed_data/scramble_merged_sites.txt", header = T)

```

Figure 5A
```{r}
repressor_color <- '#000066'
activator_color <- '#FFD700'

data <- data %>% 
    mutate(site_type_ttest_signif = ifelse(significant == T, site_type_ttest, NA))

data %>% 
    filter(!is.na(site_type_ttest_signif)) %>% 
    ggplot(aes(unscrambled_exp, relative_exp)) + 
    geom_point(data = filter(data, is.na(site_type_ttest_signif)), 
               color = 'gray38', alpha = 0.25) +
    geom_point(alpha = 0.50, aes(color = site_type_ttest_signif)) +
    scale_color_manual(values = c(repressor_color, activator_color), na.value = 'gray65') +
    scale_x_log10(breaks = c(0.01, 0.1, 1, 10, 100, 1000)) + 
    scale_y_log10(breaks = c(0.01, 0.1, 1, 10, 100)) + annotation_logticks() +
    labs(x = 'wild-type expression',
         y = 'relative expression',
         color = 'significant\nFDR-adjusted\nt-test') +
    theme(aspect.ratio = 1,
          axis.text = element_text(size = 20),
          axis.title = element_text(size = 20),
          legend.text = element_text(size = 20),
          legend.title = element_text(size = 20))

ggsave('../../figs/fig5/fig5a_scramble_ttest.pdf', unit = 'in', 
       height = 5, width = 7)
```

Figure5D - Looking at disagreed scrambles
```{r}
scrambled_merged <- read.table("../processed_data/scramble_merged_sites.txt", header = T)

disagreed_scrambles <- filter(scrambled_merged, merged_length >= 15 & merged_length <= 30 & tf_concordance != TRUE)

#TSS_4788_storz_regulondb,1234128,+ fadR gene
tss_data %>% 
    filter(tss_name == 'TSS_4788_storz_regulondb') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("#ffd700", "#000066")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.2,5)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PfadR")




```




```{r}
#TSS_8565_storz,2253110
tss_data %>% 
    filter(tss_name == 'TSS_8565_storz') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.1,10)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PyeiL")



#TSS_9376_storz,2481542 evgA
tss_data %>% 
    filter(tss_name == 'TSS_9376_storz') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,10)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PevgA")


#TSS_7718_storz, 2011167,+ A REPRESSOR THAT IS ACTUALLY AN ACTIVATOR FliF, this is actually a very cool promoter for comparing M9, LB
#This is for fliF P1 . It's possible that this is an activator for this promoter that suppresses the donwstream promoter


tss_data %>% 
    filter(tss_name == 'TSS_7718_storz') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,10)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PfliFGHIJK")



#TSS_17287_storz_regulondb, 4417950,+ ulaA gene. Not enough overlap
tss_data %>% 
    filter(tss_name == 'TSS_17287_storz_regulondb') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,100)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PfliFGHIJK")


#TSS_5764_regulondb,1486214,+ aldA. Lots more expression in LB > M9
#Only detect CRP site at 065


tss_data %>% 
    filter(tss_name == 'TSS_5764_regulondb') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,100)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PfliFGHIJK")


#TSS_7627_wanner, 2632092,-


#TSS_9893_regulondb, 2632092,-

tss_data %>% 
    filter(tss_name == 'TSS_9893_regulondb') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,100)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PfliFGHIJK")



#TSS_555_regulondb



```


Look at 50 percent sites
```{r}
scrambled_merged_50 <- read.table("../../processed_data/scramble_merged_50pct_sites.txt", header = T)

disagreed_scrambles_50 <- filter(scrambled_merged_50, site_length >= 15 & site_length <= 30 & tf_concordance != TRUE)


#Repressor
#TSS_7679_storz_regulondb, TOO MUCH MISSING DATA

tss_data %>% 
    filter(tss_name == 'TSS_7679_storz_regulondb') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,100)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PfliFGHIJK")


#TSS_1382_regulondb,331263,+ Cant really distinguish CRA site at -13.5 from the -10



#TSS_12198_wanner, 3214528,-


#subtract 30 to compare it to the regulonDB site


tss_data %>% 
    filter(tss_name == 'TSS_12198_wanner') %>%
    mutate(scramble_start = (scramble_start-90),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,100)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PfliFGHIJK")

```


Sites from scrambled50 that don't overlap -35, -10
```{r}

TSS_9046_regulondb,2403184
TSS_9893_regulondb


"TSS_2720_regulondb,703051,+_scrambled90-100_flipped,TSS_2720_regulondb,703051,+_scrambled95-105_flipped"                                                                                                                  
 [8] "TSS_3842_wanner,986314,-_scrambled65-75,TSS_3842_wanner,986314,-_scrambled70-80,TSS_3842_wanner,986314,-_scrambled75-85,TSS_3842_wanner,986314,-_scrambled85-95"    
#[11] "TSS_5764_regulondb,1486214,+_scrambled100-110,TSS_5764_regulondb,1486214,+_scrambled105-115,TSS_5764_regulondb,1486214,+_scrambled110-120"                                                                                
[16] "TSS_7097_storz_regulondb,1860759,+_scrambled75-85,TSS_7097_storz_regulondb,1860759,+_scrambled80-90,TSS_7097_storz_regulondb,1860759,+_scrambled85-95"                                                                    
[17] "TSS_7679_storz_regulondb,1999831,-_scrambled35-45,TSS_7679_storz_regulondb,1999831,-_scrambled40-50,TSS_7679_storz_regulondb,1999831,-_scrambled45-55"                                                                    
[20] "TSS_7718_storz,2011167,+_scrambled35-45_flipped,TSS_7718_storz,2011167,+_scrambled40-50_flipped,TSS_7718_storz,2011167,+_scrambled45-55_flipped,TSS_7718_storz,2011167,+_scrambled50-60_flipped"                          
[23] "TSS_9046_regulondb,2403184,-_scrambled65-75,TSS_9046_regulondb,2403184,-_scrambled70-80,TSS_9046_regulondb,2403184,-_scrambled75-85"                                                                                      
[24] "TSS_9893_regulondb,2632092,-_scrambled40-50,TSS_9893_regulondb,2632092,-_scrambled45-55,TSS_9893_regulondb,2632092,-_scrambled50-60"                                                                                      
[27] "TSS_12198_wanner,3214528,-_scrambled35-45,TSS_12198_wanner,3214528,-_scrambled40-50,TSS_12198_wanner,3214528,-_scrambled45-55,TSS_12198_wanner,3214528,-_scrambled50-60,TSS_12198_wanner,3214528,-_scrambled55-65"        
[40] "TSS_16051_wanner,4116183,-_scrambled45-55,TSS_16051_wanner,4116183,-_scrambled50-60,TSS_16051_wanner,4116183,-_scrambled55-65,TSS_16051_wanner,4116183,-_scrambled65-75"                                                  


```





Look at unannotated motifs
```{r}
scrambled_merged <- read.table("../processed_data/scramble_merged_sites.txt", header = T) 

unknown_scrambles <- filter(scrambled_merged, merged_length >= 15 & merged_length <= 30 & tfbs_left == -1)


#rpsf known Crp regulation, probably found at -90 https://biocyc.org/gene?orgid=ECOLI&id=EG10905. Unclear what +1 repressor would be 
tss_data %>% 
    filter(tss_name == 'TSS_17295_storz_regulondb') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,100)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PrpsF")

#TSS_13220_regulondb - rpsMp has good site at +1 but unclear what it is
tss_data %>% 
    filter(tss_name == 'TSS_13220_regulondb') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.05,10)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PrpsM")


#TSS_13441_storz_wanner, rpsL ribosomal subunit S12 https://biocyc.org/gene?orgid=ECOLI&id=EG10911
tss_data %>% 
    filter(tss_name == 'TSS_13441_storz_wanner') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.05,10)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PrpsL")


#TSS_6315_regulondb ydfA no known regulation

tss_data %>% 
    filter(tss_name == 'TSS_6315_regulondb') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,100)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across PydfA")

#TSS_6671_storz,1739206, TSS_6672_regulondb
a<- tss_data %>% 
    filter(tss_name == 'TSS_6671_storz') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.01,10)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across Pcfa") 

#TSS_6672_regulondb also cfa
b<-tss_data %>% 
    filter(tss_name == 'TSS_6672_regulondb') %>%
    mutate(scramble_start = (scramble_start-120),
           relative_exp = relative_exp,
           Type = ifelse(2^relative_exp > 1, 'Repressing', 'Activating')) %>% 
    ggplot(aes(scramble_start, 2^relative_exp)) +
    geom_vline(xintercept = c(0,-20,-40,-60,-80,-100, -120), linetype="dashed", alpha=.6) +
    geom_bar(aes(fill=Type),stat="identity", color = 'black', alpha = .8) +#geom_point() +
    scale_fill_manual(values = c("gold2", "purple4")) +
    #xlim(-120,30) + 
    geom_hline(yintercept = 1) + annotation_logticks(sides="l") +
    scale_y_log10(limits=c(.05,10)) +
    labs(x = 'Scramble Position', y= 'Relative Expression to WT', color = '', title = "Mutational scanning across Pcfa")
plot_grid(a,b)
```